---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/Srinivas922023/gcp.git
      - source
  - name: hashicorp/terraform:latest
    entrypoint: bash
  - name: terraform init
   
  - name: terraform plan
    
  - name: terraform apply -auto-approve
    
    
      
  
