steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: '/bin/sh'
    args:
      - 'c'
      - |
          terraform init
          terraform plan'
          terraform apply -auto-approve
      
  