steps:
  - name: 'gcr.io/cloud-builders/git'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      
      - |
          cd source/terraform
          terraform init
          terraform plan
          terraform apply -auto-approve
      
  