steps:

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      
      - |
       if [ -d "environments/$BRANCH_NAME/" ]; then
        cd environments/$BRANCH_NAME      
          terraform init
          terraform plan
          terraform apply -auto-approve
      
  