    steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: 'sh'
    steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: terraform init
    
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.0.0'
    
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform apply --auto-approve
  
