steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: '/bin/sh'
    args:
      
      - |
          cd source/terraform
          terraform init
          terraform plan
          terraform apply -auto-approve
      
  