---
steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/Srinivas922023/gcp.git
      - source
  - name: hashicorp/terraform:latest
    entrypoint: bash
  - name: terraform init
    run: terraform init
  - name: terraform plan
    run: terraform plan
  - name: terraform apply
    run: terraform apply -auto-approve
    
      
  
