steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: "sh"
    args:
      - 'terraform init'
      
  - name: 'hashicorp/terraform:latest'
    entrypoint: "sh"
    args:
      - 'terraform plan'

  - name: 'hashicorp/terraform:latest'
    entrypoint: "sh"
    args:
      - 'terraform apply'
      - '--auto-approve'

