steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - 'c'
      - 'terraform init'
      
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - 'c'
      - 'terraform plan'

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - 'c'
      - 'terraform apply'
      - '--auto-approve'

